config/routes.rb
Rails.application.routes.draw do

  root 'catalog#index'
  
  get 'zohoverify/verifyforzoho' => 'zohoverify#verifyforzoho', :defaults => { :format => "html" }
  get 'home/registration' => 'home#registration'
  get 'contact' => 'home#contact'
  match '/send_mail', to: 'home#send_mail', via: 'post'
  
  devise_for :users, :controllers => { registrations: 'users/registrations', 
                                       sessions: 'users/sessions',
                                       confirmations: 'users/confirmations',
                                       passwords: 'users/passwords'
  }
  
  post 'products/new'
  get "/fetch_products" => 'catalog#from_category', as: 'fetch_products'
  get 'catalog/show'

  get 'catalog/search'

  get 'cart' => 'cart#index', as: 'cart'
  
  post 'checkout' => 'checkout#index'
  
  get 'checkout/order' => 'checkout#order'
  
  post 'checkout/place_order'
  post 'cart/add_amount'
  get 'cart/add_amount'
  post 'products/select_category'
  post 'products/select_category'
  get 'checkout/success' => 'checkout#success'
  
  get 'orders' => 'orders#index'
  post 'orders' => 'orders#index'
  get 'my_orders' => 'orders#user_orders'
  
  post 'subcategories/create' => 'subcategories_create_path'
  
  post 'cart/add' => 'cart#add'
  post 'cart/add/:id' => 'cart#add'
  post 'cart/remove/:id' => 'cart#remove'
  post 'cart' => 'cart#index'
  post 'cart/add_amount' => 'cart#add_amount'
  resources :subcategories
  resources :products
  
  post '/update_order/:id' => "orders#update_order", as: :update_order
  
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :products, :through => :cart_items
    
  def get_total_price
    cart_items.inject(0) {|sum, item| item.price * item.amount + sum}
  end
    
  #def get_total_quantity
   # cart_items.inject(0) {|sum, item| item.amount + sum}
  #end
  
  def get_total_items
    cart_items.all.count
  end
    
  def add(product_id, color, amount)
    items = cart_items.where('product_id = ? and color = ?', 
                             product_id, color)
    product = Product.find(product_id)
      if items.size < 1
        cart_item = cart_items.create(:product_id => product_id,
                               :amount => amount,
                               :price => product.price,
                               :color => color)
      else
        cart_item = items.first
        cart_item.update_attribute(:amount, cart_item.amount + amount.to_i)
      end
      cart_item
  end
    
  def remove(product_id, color)
    cart_item = cart_items.where('product_id = ? and color = ?', product_id, color).first
    CartItem.destroy(cart_item)
    cart_item
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :initialize_cart
    
  def index
    if @cart.get_total_items == 0
      redirect_to root_path
    end
    @button_text = 'Registracija'
    if current_user
      @button_text = 'Nastavi'
    end
    @step_text = step_text
  end
    
  def add
      @product = Product.get_product(params[:product][:id])
      amount = params[:amount]
      color = params[:color]
      if @product.check_attachment_availability(color) and amount.to_f.between?(0.5, 999)
        @item = @cart.add(@product.id, color, amount)
        flash[:success] = %Q[Proizvod je dodat u korpu.]
      else
        if amount.to_f <= 0 or amount.to_f > 999
          flash[:danger] = "Količina koju ste uneli ne može se dodati u korpu."
        else
          flash[:danger] = "Ovaj proizvod ne možete dodati u korpu."
        end
      end
      redirect_to catalog_show_path(id: @product.id)
  end
    
  def add_amount
    if params[:item] and params[:amount]
      @item = CartItem.find(params[:item])
      @item.amount = params[:amount]
      @item.save!
    end
    respond_to do |format|  
      format.js 
    end  
  end
    
  def remove
    @product = Product.find(params[:id])
    @item = @cart.remove(params[:id], params[:color])
    redirect_to cart_path
  end
    
  def initialize_cart
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
  
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_cart.html.erb
<li id="cart-trigger">
  <a>
    <span class="glyphicon glyphicon-shopping-cart fs14"></span>
    <span class="cart-indicator">
      <% if @cart && @cart.get_total_items > 0 %>
        <%= @cart.get_total_items %>
      <% end %>
    </span>
  </a>
</li>
<div class="cart-widget">
  <span id="cart-widget-dismiss" class="glyphicon glyphicon-remove pointer">
  </span>
  <% if @cart == nil || @cart.get_total_items == 0 %>
    <div class="cart-widget-content">Vaša korpa je prazna.</div>
    <div class="cart-action-button">
      <a class="cart-link" href="/">Idi na katalog</a>
    </div>
  <% else %>
  <div class="cart-widget-content">
      <span>Broj proizvoda u korpi:</span>
      <span class="link-c b"><%= @cart.get_total_items %></span>
      <span>Ukupan iznos korpe:</span> 
      <span class="link-c b">
        <%= render partial: 'shared/price_format', 
                   locals: { price: @cart.get_total_price} %>
      </span>
  </div>
  <div class="cart-action-button">
    <a class="cart-link" href="/cart">Idi na korpu</a>
  </div> 
  <% end %>
  
  
</div>

app/views/cart/_checkout_cart.html.erb
<div class="cart-list-head ct col-md-12 col-sm-12 col-xs-12">
  VREDNOST KORPE
</div>
<% for item in @cart.cart_items %>
  <%= render :partial => "cart/checkout_item", :locals =>{:object => item} %>
<% end %>
<div class="col-md-12 cart-list-item">
  <div class="col-md-12  ct">
    Sveukupno:
  </div>
  <% if delivery == 'true' %>
    <div class="col-md-6 b ct mt18 fs16 no-padding">
      <%= render partial: 'shared/price_format', 
                 locals: { price: @cart.get_total_price} %>  
    </div>
    <div class="col-md-6 mt18 post-exp no-padding">
      <span>+ troškovi poštarine</span>
    </div>
    <div class="col-md-12 mt18">
      <span class="light-text">
        NAPOMENA: Za svaku kupovinu koja prelazi 3.000 RSD troškove poštarine plaćamo mi.
      </span>
    </div>
  <% else %>
    <div class="col-md-12 b ct mt18 fs16 no-padding">
      <%= render partial: 'shared/price_format', 
                 locals: { price: @cart.get_total_price} %>
    </div>
    <div class="col-md-12 mt18">
      <span class="light-text">
        Informacije o adresi i radnom vremenu našeg prodajnog mesta možete naći na 
        <%= link_to 'kontakt stranici', contact_path %>.
      </span>
    </div>
  <% end %>
</div>

app/views/cart/_checkout_item.html.erb
<div class="col-md-12 cart-list-item">
  <div class="col-md-12 no-padding mb5">
    <%= object.product.name %>
  </div>
  <div class="col-md-6 light-text no-padding">
    <%= render partial: 'shared/price_format', 
               locals: { price: object.price} %> x <%= object.amount %>
    <% object.product.get_measure_amount %>
  </div>
  <div class="col-md-6 no-padding fs14" style="line-height: 1.2">
    = <%= render partial: 'shared/price_format', 
                 locals: { price: object.get_total_price} %> 
  </div>
</div>

app/views/cart/_item.html.erb
<div class="cart-list-item col-md-12 col-sm-12 col-xs-12">
  <div class="col-md-2 col-sm-2 col-xs-12">
    <%= image_tag(object.chosen_image,
                  class: "image item-image cart-item-image") %>
  </div>
  <div class="col-md-4 col-sm-4 col-xs-12 va-parent va-parent-height_84">
    <div class="va-child">
      <%= object.product.name %> (<%= object.color %>)
      <br>
      <span class="light-text"> 
        <span id = "cena"> 
          <%= render partial: 'shared/price_format', 
                     locals: { price: object.price} %>
        </span>  
        <% object.product.get_measure_type %>
      </span> 
    </div>
    <div class="va-helper"></div>
  </div>
  <%= form_tag "/cart/add_amount", method: :post, id: "amount_form", 
    :remote => true do %>
    <div class="col-md-2 col-sm-2 col-xs-12 ct va-parent va-parent-height_84">
      <div class="va-child">
        <%= hidden_field_tag :item,  object.id, id: "item_id" %>
        <% if object.product.piece %>
          <%= text_field_tag :amount, object.amount, 
                             class:"form-control ct b fs16 link-c tft", 
                             id: object.id, 
                             placeholder: "komada",
                             min: '1', 
                             type: 'number', 
                             step: '1' %>
        <% else %>
          <%= text_field_tag :amount, 
                             object.amount, 
                             class:"form-control ct b fs16 link-c tft", 
                             id: object.id, 
                             placeholder: "metra",
                             min: '0.5', 
                             type: 'number', 
                             step: '0.5'%>
        <% end %>
        <%= object.product.get_measure_amount %>
      </div>
      <div class="va-helper"></div>
    </div>
  <%end%>
  <div class="col-md-3 col-sm-3 col-xs-12 ct va-parent va-parent-height_84">
    <div id = "price_<%= object.id %>" class="va-child">
      <%= sprintf("%0.2f", object.get_total_price) %> RDS
    </div>
    <div class="va-helper"></div>
  </div>
  <div class="col-md-1 col-sm-1 col-xs-12 va-parent va-parent-height_84">
    <div class="va-child">
      <%= button_to controller: "cart",
                    action: "remove", 
                    id: object.product, 
                    color: object.color do %>
        <span class="glyphicon glyphicon-remove light-text cart-remove-prod">
        </span>
      <% end %>
    </div>
    <div class="va-helper"></div>
  </div>
</div>

app/views/cart/add_amount.js.erb
$("#price_<%= @item.id %>").text("<%= j render partial: 'shared/price_format', 
                                             locals: { price: @item.get_total_price} %> ");
$("#tot-price").text("<%= j render partial: 'shared/price_format', 
                                 locals: { price: @cart.get_total_price} %> ");

app/views/cart/index.html.erb
<%= render "shared/wizard_steps", steps: [1, 0, 0], checks: [0, 0, 0] %>
<div class="alert-msgs hide-at-first col-md-12">
</div>
<div class="cart-section col-md-12 col-sm-12 col-xs-12"> <!--CART SECTION-->
    <div class="row">
        <div class="cart-list col-md-8 col-sm-12 col-xs-12">
            <div class="cart-list-head col-md-12 col-sm-12 col-xs-12 ct">
                <div class="col-md-6 col-name">
                    PROIZVOD
                </div>
                <div class="col-md-2 col-name">
                    KOLIČINA
                </div>
                <div class="col-md-3 col-name">
                    UKUPNO
                </div>
                <div class="col-md-1 col-name">
                </div>
            </div>
            <% @cart.cart_items.each do |item| %>
                <%= render "item", object: item %>
            <% end %>
        </div>
        <div class="card col-md-4 col-sm-12 col-xs-12"><!--CART TOTAL-->
            <div class="cart-list-head ct col-md-12">
                    VREDNOST KORPE
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12 fs14 cart-list-item">
                <div class="col-md-4 ct">
                    Dostava:
                </div>
            <%= form_tag checkout_path do %>
                <div class="col-md-8">
                    <div class="radio">
                        <label>
                            <%= radio_button_tag :delivery, 
                                                 true, 
                                                 :checked => true %>
                                Slanje poštom
                        </label>
                    </div>
                    <div class="radio no-mb">
                        <label>
                            <%= radio_button_tag :delivery, false %>
                                Lično preuzimanje
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12 cart-list-item">
                <div class="col-md-12 ct">
                    Sveukupno:
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6 b mt18 ct no-padding" id="tot-price">
                    <%= render partial: 'shared/price_format', 
                               locals: { price: @cart.get_total_price} %>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-6 mt18 post-exp no-padding" id="post-div1">
                    <span>+ troškovi poštarine</span>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12 mt18">
                    <span class="light-text" id="post-div2">
                        NAPOMENA: Za svaku kupovinu koja prelazi 3.000 RSD troškove poštarine plaćamo mi.
                    </span>
                    <span class="light-text hide-at-first" id="store-div2">
                        Informacije o adresi i radnom vremenu našeg prodajnog mesta možete naći na <%= link_to 'kontakt stranici', contact_path %>.
                    </span>
                </div>
            </div>
            <div class="cart-submit-wrap col-md-12 col-sm-12 col-xs-12 ct">
                <%= button_tag type: "submit", 
                               class: "button button-submit" do %>
                    <span class='glyphicon glyphicon-repeat spin hide-at-first'>
                    </span>
                    <%= @button_text %> 
                    <span class="glyphicon glyphicon-triangle-right fs14">
                    </span>
                <% end %>
            <% end %>
           </div>
        </div>
    </div>
</div>