config/routes.rb
Rails.application.routes.draw do

  root 'catalog#index'
  
  get 'zohoverify/verifyforzoho' => 'zohoverify#verifyforzoho', :defaults => { :format => "html" }
  get 'home/registration' => 'home#registration'
  get 'contact' => 'home#contact'
  match '/send_mail', to: 'home#send_mail', via: 'post'
  
  devise_for :users, :controllers => { registrations: 'users/registrations', 
                                       sessions: 'users/sessions',
                                       confirmations: 'users/confirmations',
                                       passwords: 'users/passwords'
  }
  
  post 'products/new'
  get "/fetch_products" => 'catalog#from_category', as: 'fetch_products'
  get 'catalog/show'

  get 'catalog/search'

  get 'cart' => 'cart#index', as: 'cart'
  
  post 'checkout' => 'checkout#index'
  
  get 'checkout/order' => 'checkout#order'
  
  post 'checkout/place_order'
  post 'cart/add_amount'
  get 'cart/add_amount'
  post 'products/select_category'
  post 'products/select_category'
  get 'checkout/success' => 'checkout#success'
  
  get 'orders' => 'orders#index'
  post 'orders' => 'orders#index'
  get 'my_orders' => 'orders#user_orders'
  
  post 'subcategories/create' => 'subcategories_create_path'
  
  post 'cart/add' => 'cart#add'
  post 'cart/add/:id' => 'cart#add'
  post 'cart/remove/:id' => 'cart#remove'
  post 'cart' => 'cart#index'
  post 'cart/add_amount' => 'cart#add_amount'
  resources :subcategories
  resources :products
  
  post '/update_order/:id' => "orders#update_order", as: :update_order
  
  

end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :find_cart
  before_action :set_no_cache, except: :success
  after_action :delete_cart, only: :success
  protect_from_forgery with: :null_session
    
  def index
    @delivery = params[:delivery]
    @flag = 'checkout'
    if current_user
      redirect_to :action => 'order', :delivery => @delivery
    end
    
    @step_text = step_text
  end
    
  def order
    @step_text = step_text
    @user = ""
    @company_data = ""
    @delivery = params[:delivery]
    if params[:id]
      id = Hashids.new("kashmeresaltforkashmere", 10).
        decode(params[:id]).
        try(:first)
      @user = User.find(id)
      @company_data = @user.company_data
    elsif current_user
      @user = current_user
      @company_data = @user.company_data
    end
  end
    
  def success
    @order = Order.last()
    @step_text = step_text
  end
    
  def place_order
    order = Order.new(order_params)
    order.customer_ip = request.remote_ip
    cart = Cart.find(params[:order][:cart])
    populate_order(cart, order)
    if Order.count > 0
      id = Order.last.id + 1
    else
      id = 1
    end
    number = order.generate_order_number(id)
    order.order_number = number
    session[:order_number] = number
        
    if order.save
      cart.cart_items.destroy_all
      redirect_to checkout_success_path
      OrderMailer.order_confirmation(order).deliver
    else
      flash[:notice] = "Error while placing order.'#{order.error_message}'"
      render :action => 'index'
    end
  end
    
    
  def check_cart
    if @cart.number_of_items == 0
      redirect_to root_path
    end
  end
  private
  
    def populate_order(cart, order)
      for cart_item in cart.cart_items
        order_item = OrderItem.new(:product_id => cart_item.product_id,
                                   :price => cart_item.price,
                                   :amount => cart_item.amount,
                                   :color => cart_item.color)
        order.order_items << order_item
      end
    end
        
    def order_params
      params.require(:order).permit(:company, :delivery, :ship_to_company_name, 
                                    :pib, :crn, :id, :email, :customer_ip, 
                                    :ship_to_first_name, :ship_to_last_name, 
                                    :phone_number, :ship_to_address, 
                                    :ship_to_city, :ship_to_postal_code, 
                                    :error_message, :updated_at, :created_at)
    end
    
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/index.html.erb
<%= render "shared/wizard_steps", steps: [0, 1, 0], checks: [1, 0, 0] %>
<div class="alert-msgs hide-at-first col-md-12">
</div>
<div class="cart-section col-md-12"> <!--CART SECTION-->
    <div class="row">
        <div class="col-md-8">
            <div class="cart-list-head col-md-12 ct">
                REGISTRACIJA KUPCA
            </div>
            <div class="types-of-accounts col-md-12">
                <div class="col-md-4">
                    <span id="login-btn" class="cool-link-active">
                       <div class="button button-default">
                            Uloguj se
                        </div>
                    </span>
                </div>
                <div class="col-md-4">
                    <span id="register-btn" class="cool-link">
                        <div class="button button-default">
                            Napravi novi nalog
                        </div>
                    </span>
                </div>
                <div class="col-md-4">
                    <span id="guest-btn" class="cool-link">
                        <div class="button button-default">
                            Bez registracije
                        </div>
                    </span>
                </div>
            </div>
            <%= render partial: 'users/sessions/login'%>
            <div class="hide-at-first  col-md-12" id="register-div"><!--REG FORM--> 
                <%= render partial: 'users/registrations/register'%>
            </div>
            <%=form_for :order, url: checkout_place_order_path do |f| %>
                <%= hidden_field :order, :delivery, value: @delivery %>
                <div class="hide-at-first  col-md-12" id="guest-div"><!--GUEST FORM--> 
                    <div class="col-md-12">
                        <div class="col-md-4">
                            Lični podaci:
                        </div>
                        <div class="col-md-4 radio">
                            <label>
                                <%= f.radio_button :company, 
                                                   false, 
                                                   checked: true %>
                                    Fizičko lice
                            </label>
                        </div>
                        <div class="col-md-4 radio">
                            <label>
                                <%= f.radio_button :company, true %>
                                    Pravno lice
                            </label>
                        </div>
                    </div>
                    <div class="col-md-12 hide-at-first mt18" 
                         id="guest-company">
                        <div class="col-md-4">
                            <%= f.text_field :ship_to_company_name, 
                                             autofocus: true, 
                                             class: "form-control link-c b company-register", 
                                             placeholder: "*Naziv firme" %>
                        </div>
                        <div class="col-md-4">
                        <%= f.text_field :pib, 
                                         autofocus: true, 
                                         class: "form-control link-c b company-register", 
                                         placeholder: "*PIB" %>
                        </div>         
                        <div class="col-md-4">
                            <%= f.text_field :crn, 
                                             autofocus: true, 
                                             class: "form-control link-c b", 
                                             placeholder:"*Matični broj firme company-register" %>
                        </div>    
                    </div>
                    <div class="mt18 col-md-12">
                        <div class="col-md-4">
                            <%= f.text_field :ship_to_first_name, 
                                             class:"form-control link-c b validation-order", 
                                             placeholder:"*Ime" %>
                        </div>
                        <div class="col-md-4">
                            <%= f.text_field :ship_to_last_name, 
                                             class:"form-control link-c b validation-order", 
                                             placeholder:"*Prezime" %>
                        </div>
                    </div>
                    <div class="col-md-12 mt18">
                        <div class="col-md-4">
                            <%= f.text_field :email, 
                                             class:"form-control link-c b validation-order", 
                                             placeholder:"*E-mail adresa" %>
                        </div>
                        <div class="col-md-4">
                            <%= f.text_field :phone_number, 
                                             class:"form-control link-c b validation-order", 
                                             placeholder:"*Kontakt telefon" %>
                        </div>
                    </div>
                    <% if @delivery == 'true' %>
                        <div class="col-md-12 mt18">
                            <div class="col-md-4">
                                <%= f.text_field :ship_to_address, 
                                                 class:"form-control link-c b validation-order", 
                                                 placeholder:"*Adresa za pošiljku" %>
                            </div>
                            <div class="col-md-4">
                                <%= f.text_field :ship_to_city, 
                                                 class: "form-control link-c b validation-order", 
                                                 placeholder: "*Grad" %>
                            </div>
                            <div class="col-md-4">
                                <%= f.text_field :ship_to_postal_code, 
                                                 class: "form-control link-c b validation-order", 
                                                 placeholder: "*Poštanski broj" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>  
            <div class="card col-md-4"><!--CART TOTAL-->
                <% if @cart %>
                    <%= render partial: '/cart/checkout_cart', 
                               locals: {:delivery => @delivery} %>
                    <%= hidden_field :order, :cart, value: @cart.id %>
                <% end %>
                <div class="cart-submit-wrap col-md-12 ct">
                    <%= button_tag type: "submit", 
                                   class: "button button-submit",
                                   id: "btn-order" do %>
                        <span class='glyphicon glyphicon-repeat spin hide-at-first'>
                        </span>
                        Naruči
                        <span class="glyphicon glyphicon-ok fs14"></span>
                    <% end %>
               </div>
            </div>
        <% end %>
    </div>
</div>

app/views/checkout/order.html.erb
<%= render "shared/wizard_steps", steps: [0, 1, 0], checks: [1, 0, 0] %>
<div class="alert-msgs hide-at-first col-md-12">
</div>
<%if @user != "" %>
    <div class="cart-section col-md-12"> <!--CART SECTION-->
        <div class="row">
            <div class="col-md-8">
                <div class="cart-list-head col-md-12 ct mb22">
                    PODACI KUPCA
                </div>
                <div class="col-md-12" id="multilog-div"><!--REG FORM--> 
                    <div class="col-md-12">
                        <div class="col-md-4">
                            Lični podaci:
                        </div>
                    </div>
                    <form method="post" 
                          id="checkout" 
                          action="<%= url_for :action => :place_order %>">
                        <%= hidden_field :order, :delivery, value: @delivery %>
                        <%= hidden_field :order, 
                                         :company, 
                                         value: @user.company %>
                        <% if @user.company %>
                            <div class="col-md-12 mt18" id="guest-company">
                                <div class="col-md-4">
                                    <%= text_field :order, 
                                                   :ship_to_company_name, 
                                                   value: @company_data.company_name, 
                                                   autofocus: true, 
                                                   class: "form-control link-c b", 
                                                   placeholder: "*Naziv firme" %>
                                </div>
                                <div class="col-md-4">
                                   <%= text_field :order, 
                                                  :pib, 
                                                  autofocus: true, 
                                                  value: @company_data.pib, 
                                                  class: "form-control link-c b", 
                                                  placeholder: "*PIB" %>
                                </div>         
                            </div>
                        <% end %>
                        <div class="mt18 col-md-12">
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :ship_to_first_name, 
                                               value: @user.first_name, 
                                               class:"form-control link-c b", 
                                               placeholder:"*Ime" %>
                            </div>
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :ship_to_last_name, 
                                               value: @user.last_name, 
                                               class:"form-control link-c b", 
                                               placeholder:"*Prezime" %>
                            </div>
                        </div>
                        <div class="col-md-12 mt18">
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :email, 
                                               value: @user.email, 
                                               class:"form-control link-c b", 
                                               placeholder:"*E-mail adresa" %>
                            </div>
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :phone_number, 
                                               value: @user.phone_number, 
                                               class:"form-control link-c b", 
                                               placeholder:"*Kontakt telefon" %>
                            </div>
                        </div>
                        <div class="col-md-12 mt18">
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :ship_to_address, 
                                               value: @user.address, 
                                               class:"form-control link-c b", 
                                               placeholder:"*Adresa za pošiljku" %>
                            </div>
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :ship_to_city, 
                                               value: @user.city,  
                                               class:"form-control link-c b", 
                                               placeholder:"*Grad" %>
                            </div>
                            <div class="col-md-4">
                                <%= text_field :order, 
                                               :ship_to_postal_code, 
                                               value: @user.postal_code, 
                                               class:"form-control link-c b", 
                                               placeholder:"*Poštanski broj" %>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card col-md-4"><!--CART TOTAL-->
                    <% if @cart %>
                        <%= render partial: '/cart/checkout_cart', 
                                   locals: {:delivery => @delivery} %>
                        <%= hidden_field :order, :cart, value: @cart.id %>
                    <% end %>
                    <div class="cart-submit-wrap col-md-12 ct">
                        <%= button_tag type: "submit", 
                                       class: "button button-submit" do %>
                            <span class='glyphicon glyphicon-repeat spin hide-at-first'>
                            </span>
                            Naruči 
                            <span class="glyphicon glyphicon-ok fs14"></span> 
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </form>
                    <%else%>
                        Greska!
                    <%end%>

app/views/checkout/success.html.erb
<%= render "shared/wizard_steps", steps: [0, 0, 1], checks: [1, 1, 1] %>
<div class="msgs success-msgs col-md-12 col-sm-12 col-xs-12 mt18">
    Vaša narudžbina je primljena!
</div>
<div class="col-md-12 col-sm-12 col-xs-12 purchase-summary">
    <div class="col-md-3 summary-block ct">
        <span>ŠIFRA NARUDŽBINE:</span><br>
        <strong><%= @order.order_number %></strong>
    </div>
    <div class="col-md-3 summary-block ct">
        <span>DATUM NARUDŽBINE:</span><br>
        <strong><%= @order.created_at.strftime('%d/%m/%Y') %></strong>
    </div>
    <div class="col-md-3 summary-block ct">
        <span>UKUPNO:</span><br>
        <strong>
        <%= render partial: 'shared/price_format', 
            locals: { price: @order.get_total_price} %>
        </strong>
    </div>
    <div class="col-md-3 summary-block ct"> <%# dodati if %>
        <span>DOSTAVA:</span><br>
        <strong><%= @order.delivery_type %></strong>
       
        
    </div>
</div>
<div class="cart-section col-md-12 col-sm-12 col-xs-12"> <!--CART SECTION-->
    <div class="row">
        <div class="col-md-4">
            <div class="cart-list-head col-md-12 col-sm-12 col-xs-12 ct ">
                PODACI KUPCA
            </div>
               <div class="mt18 col-md-12">
                <ul>
                    <% if @order.company %>
                    <li>
                        <span class="info-label">Firma: </span><%= @order.ship_to_company_name %>
                    </li>
                    <li>
                        <span class="info-label">PIB: </span><%= @order.pib %>
                    </li>
                    <li>
                        <span class="info-label">Matični broj: </span><%= @order.crn %>
                    </li>
                    <%end%>
                    <li>
                        <span class="info-label">Ime: </span><%= @order.ship_to_first_name %>
                    </li>
                    <li>
                        <span class="info-label">Prezime: </span><%= @order.ship_to_last_name %>
                    </li>
                    <li>
                        <span class="info-label">Email adresa: </span><%= @order.email %>
                    </li>
                    <li>
                        <span class="info-label">Kontakt telefon: </span><%= @order.phone_number %>
                    </li>
                    <% if @order.delivery %>
                    <li>
                        <span class="info-label">Adresa za pošiljku: </span><%= @order.ship_to_address %>
                    </li>
                    <li>
                        <span class="info-label">Grad: </span><%= @order.ship_to_city %>
                    </li>
                    <li>
                        <span class="info-label">Poštanski broj: </span><%= @order.ship_to_postal_code %>
                    </li> 
                    <% end %>
                </ul>
            </div>
        </div>
        <div class="col-md-8">
            <div class="cart-list-head col-md-12 col-sm-12 col-xs-12 ct">
                DETALJI NARUDŽBINE
            </div>
            <% @order.order_items.each do |item| %>
            <div class="cart-list-item col-md-12 col-sm-12 col-xs-12">
                <div class="col-md-1 product-image">
                    <%= image_tag(item.chosen_image, class: "image item-image summary-item-image") %>
                </div>
                <div class="col-md-11 col-sm-12 col-xs-12">
                    <div class="col-md-12 col-sm-12 col-xs-12 no-padding">
                        <%= item.get_product_name %> <%= item.color %>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6 light-text no-padding">
                        <%= render partial: 'shared/price_format', 
                            locals: { price: item.price} %>
                         x <%= item.amount %> <%= item.get_product_measure %>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6 light-text tar" style="line-height:1">
                        = <%= render partial: 'shared/price_format', 
                              locals: { price: item.get_total_price} %>
                    </div>
                </div>
            </div>
            <% end %>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="col-md-6 col-sm-6 col-xs-12 pull-right summary-box">
                    <span class="light-text fs16">UKUPNO:</span>
                    <br>
                    <strong class="fs20"> 
                    <%= render partial: 'shared/price_format', 
                        locals: { price: @order.get_total_price} %>
                    </strong>
                    <br>
                    <% if @order.delivery_type == true %>
                    <span class="light-text">+ troškovi poštarine</span>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>