config/routes.rb
Rails.application.routes.draw do

  root 'catalog#index'
  
  get 'zohoverify/verifyforzoho' => 'zohoverify#verifyforzoho', :defaults => { :format => "html" }
  get 'home/registration' => 'home#registration'
  get 'contact' => 'home#contact'
  match '/send_mail', to: 'home#send_mail', via: 'post'
  
  devise_for :users, :controllers => { registrations: 'users/registrations', 
                                       sessions: 'users/sessions',
                                       confirmations: 'users/confirmations',
                                       passwords: 'users/passwords'
  }
  
  post 'products/new'
  get "/fetch_products" => 'catalog#from_category', as: 'fetch_products'
  get 'catalog/show'

  get 'catalog/search'

  get 'cart' => 'cart#index', as: 'cart'
  
  post 'checkout' => 'checkout#index'
  
  get 'checkout/order' => 'checkout#order'
  
  post 'checkout/place_order'
  post 'cart/add_amount'
  get 'cart/add_amount'
  post 'products/select_category'
  post 'products/select_category'
  get 'checkout/success' => 'checkout#success'
  
  get 'orders' => 'orders#index'
  post 'orders' => 'orders#index'
  get 'my_orders' => 'orders#user_orders'
  
  post 'subcategories/create' => 'subcategories_create_path'
  
  post 'cart/add' => 'cart#add'
  post 'cart/add/:id' => 'cart#add'
  post 'cart/remove/:id' => 'cart#remove'
  post 'cart' => 'cart#index'
  post 'cart/add_amount' => 'cart#add_amount'
  resources :subcategories
  resources :products
  
  post '/update_order/:id' => "orders#update_order", as: :update_order
  
  

end

app/views/shared/_admin_modal.html.erb
<div class="modal fade" id="admin-modal" tabindex="-1" role="dialog" aria-labelledby="admin-modallabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title ct" id="admin-modallabel">Administrator</h4>
      </div>
      <div class="modal-body">
        <div class="row pdg5">
          <div class="col-md-6 pdg5">
            <%= link_to orders_path do %>
            <div class="box-links">
            <span class="glyphicon glyphicon-euro box-icon"></span>
            NARUDŽBINE
          </div>
          <%end%>
        </div>
          <div class="col-md-6 pdg5">
            <%= link_to products_path do %>
            <div class="box-links">
            <span class="glyphicon glyphicon-scissors box-icon"></span>
            PROIZVODI
          </div>
          <%end%>
        </div>
          <div class="col-md-6 pdg5">
            <%= link_to subcategories_path do %>
            <div class="box-links">
            <span class="glyphicon glyphicon-th-list box-icon"></span>
            KATEGORIJE
          </div>
          <%end%>
        </div>
          <div class="col-md-6 pdg5">
            <%= link_to destroy_user_session_path, method: :delete do%>
            <div class="box-links">
            <span class="glyphicon glyphicon-log-out box-icon"></span>
            IZLOGUJ SE
          </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/shared/_flash_notice.html.erb
<% flash.each do |name, msg| %>
  <% name == 'alert' ? name='danger':''%>
  <% name == 'notice' ? name='info':'' %>
  <%= content_tag :div, class: "col-md-12 alert alert-" + name, id: 'flash' do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= msg %>
  <% end %>
<% end %>

app/views/shared/_navigation.html.erb
<div class="side-menu-shade"></div>
<div id="side-menu" class="scrollbar"><!--Side menu start------------------------------------------------->
  <div class="menu-search-wrap b-line">
    <span class="search-btn-gl glyphicon glyphicon-search"></span>
      <%= form_tag( "/", method: :get, name: "search_form", style:"display:inline-block") do %>
        <%= render partial: 'shared/search' %>
      <% end %>
  </div>
  <% Category.get_all.each do |cat|%>
    <div id="m-cat-<%= cat.id %>" class="menu-option-wrap">
      <%= cat.name %>
      <span class="glyphicon glyphicon-triangle-right pull-right light-text"></span>
    </div>
    <ul id="m-menu-<%= cat.id %>" class="m-submenu">
      <% cat.subcategories.each do |sub|%>
        <li>
          <%= link_to root_path(:sub => sub.id) do %> 
          <%= sub.name %>
          <% end %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <% unless current_user %>
    <div class="menu-option-wrap t-line">
      <span class="glyphicon glyphicon-user light-text mr6"></span>
      <a href="/home/registration">Registracija</a>
    </div>
  <% end %>
  <% if current_user %>
    <% if current_user.admin %>
    <div class="menu-option-wrap t-line">
      <span class="glyphicon glyphicon-user light-text mr6"></span>
      <a data-toggle="modal" data-target="#admin-modal" class="close-menu">Admin</a>
      <span class="my-account-name">~ <%= get_username %></span>
    </div>
    <% else %>
    <div class="menu-option-wrap t-line">
      <span class="glyphicon glyphicon-user light-text mr6"></span>
      <a data-toggle="modal" data-target="#user-modal" class="close-menu">Moj Nalog</a>
      <span class="my-account-name">~ <%= get_username %></span>
    </div>
    <% end %>
  <% end %>
  <div class="menu-option-wrap t-line b-line">
    <a href="/contact" >Kontakt</a>
  </div>
</div>
<nav class="navbar nav navbar-fixed-top <%= set_home_class('transparent-nav') %>"><!--Navbar start------------------------------------->
  <div class="container nav-container">
    <div id="menu-icon" class="col-sm-4 col-xs-4 mobile-nav-icons pointer">
      <span class="glyphicon glyphicon-menu-hamburger "></span>
    </div>
    <div class="col-md-3 col-sm-4 col-xs-4 full-height logo-wrap">
      <%= link_to root_path, class:"navbar-brand " + set_home_class('invert-navbar-brand') do %> 
        KAŠMIR<span class="logo2 <%= set_home_class('invert-logo2') %>">metraža</span>
      <% end %>
    </div>
    <div class="col-sm-4 col-xs-4 mobile-nav-icons">
      <a class="pull-right" href="/cart">
        <span class="glyphicon glyphicon-shopping-cart"></span>
      </a>
    </div>
    <div class="col-md-6 nav-section">
      <ul>
      <% Category.get_all.each do |cat|%>
        <li class="capstext cool-link" id="cat-<%= cat.id %>">
            <%= link_to root_path(:cat => cat.id) do %><%= cat.name %><% end %>
            <div id="menu-<%= cat.id %>" class="catalog-menu">
              <div class="fluid-container">
                <div class="row">
                  <div class="col-md-12 menu-section">
                      <% count = 0 %>
                      <% total_subs = sub_per_column(cat.id) %>
                      <% cat.subcategories.each do |sub|%>
                      <% if count % total_subs == 0 %>
                        <div class="col-md-4">
                          <ul>
                      <% end %>
                            <li>
                              <%= link_to root_path(:sub => sub.id) do %> 
                              <%= sub.name %>
                              <% end %>
                            </li>
                      <% if count % total_subs == total_subs -  1%>
                          </ul>
                        </div>
                      <% end %>
                      <% count += 1%>
                      <% end %>
                  </div>
                </div>
              </div>
            </div>
        </li>
      <% end %>
      </ul>
    </div>
      <div class="col-md-3 nav-section">
      <ul class="navbar-right">
        <% unless current_user %>
        <li><a href="/home/registration">Registracija</a></li>
        <% end %>
        <% if current_user %>
          <% if current_user.admin %>
        <li class='hide-cat pointer'><a data-toggle="modal" data-target="#admin-modal">Admin</a></li> 
        <% else %>
        <li class="hide-cat pointer"><a data-toggle="modal" data-target="#user-modal">Moj Nalog</a></li>
        <% end %>
        <% end %>
        <li><a href="/contact" >Kontakt</a></li>
        <li id="search-trigger">
          <a>
            <span class="glyphicon glyphicon-search fs14">
          </a>
        </li>
        <div class="search-box">
          <span class="search-btn-gl glyphicon glyphicon-search"></span>
            <%= form_tag( "/", method: :get, name: "search_form", style:"display:inline-block") do %>
              <%= render partial: 'shared/search' %>
            <% end %>
        </div>
        <%= render partial: 'cart/cart' %>
        
      </ul>
      </div>
  </div>
</nav> <!--Navbar end-->

app/views/shared/_price_format.html.erb
<% if price % 1 == 0 %>
    <%= number_with_precision(price, delimiter: '.', precision: 0) %> RSD
<% else %>
    <%= number_with_precision(price, delimiter: '.', precision: 2, separator: ',') %> RSD
<% end %>

app/views/shared/_search.html.erb
<%= text_field_tag :q, '', class: 'form-control user-search link-c b clearable', 
    placeholder: 'Pretraži proizvode...', value: @search_term %>

app/views/shared/_user_modal.html.erb
<div class="modal fade" id="user-modal" tabindex="-1" role="dialog" aria-labelledby="user-modallabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <% if current_user %>
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        
        <h4 class="modal-title ct" id="user-modallabel"><%= current_user.get_full_name%></h4>
      </div>
      
      <div class="modal-body">
        <div class="row pdg5">
          <div class="col-md-6 pdg5">
            <%= link_to edit_user_registration_path(current_user.id) do %>
            <div class="box-links">
              <span class="glyphicon glyphicon-user box-icon"></span>
              MOJI PODACI
            </div>
            <%end%>
          </div>
          <div class="col-md-6 pdg5">
            <%= link_to my_orders_path do %>
              <div class="box-links">
              <span class="glyphicon glyphicon-shopping-cart box-icon"></span>
              MOJE NARUDŽBINE
            </div>
            <%end%>
          </div>
          <div class="col-md-12 pdg5">
            <%= link_to destroy_user_session_path, method: :delete do%>
              <div class="box-links">
              <span class="glyphicon glyphicon-log-out box-icon"></span>
              IZLOGUJ SE
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
          </div>

app/views/shared/_wizard_steps.html.erb
<div class="page-head-sm col-md-12 col-sm-12 col-xs-12">
   <span class="col-md-4 col-sm-4 col-xs-12 <%= steps[0] == 1 ? 'current-page':'non-current-page' %>">1. Korpa 
       <% if checks[0] == 1 %>
           <span class="glyphicon glyphicon-ok fs20"></span>
       <% end %>
   </span> 
   <span class="col-md-4 col-sm-4 col-xs-12 <%= steps[1] == 1 ? 'current-page':'non-current-page' %>">2. <%= @step_text %> 
   <% if checks[1] == 1 %>
           <span class="glyphicon glyphicon-ok fs20"></span>
       <% end %>
   </span> 
   <span class="col-md-4 col-sm-4 col-xs-12 <%= steps[2] == 1 ? 'current-page':'non-current-page' %>">3. Potvrda kupovine 
   <% if checks[2] == 1 %>
           <span class="glyphicon glyphicon-ok fs20" style="color:rgba(67, 177, 67, 0.78)"></span>
       <% end %>
    </span>
</div>