config/routes.rb
Rails.application.routes.draw do

  root 'catalog#index'
  
  get 'zohoverify/verifyforzoho' => 'zohoverify#verifyforzoho', :defaults => { :format => "html" }
  get 'home/registration' => 'home#registration'
  get 'contact' => 'home#contact'
  match '/send_mail', to: 'home#send_mail', via: 'post'
  
  devise_for :users, :controllers => { registrations: 'users/registrations', 
                                       sessions: 'users/sessions',
                                       confirmations: 'users/confirmations',
                                       passwords: 'users/passwords'
  }
  
  post 'products/new'
  get "/fetch_products" => 'catalog#from_category', as: 'fetch_products'
  get 'catalog/show'

  get 'catalog/search'

  get 'cart' => 'cart#index', as: 'cart'
  
  post 'checkout' => 'checkout#index'
  
  get 'checkout/order' => 'checkout#order'
  
  post 'checkout/place_order'
  post 'cart/add_amount'
  get 'cart/add_amount'
  post 'products/select_category'
  post 'products/select_category'
  get 'checkout/success' => 'checkout#success'
  
  get 'orders' => 'orders#index'
  post 'orders' => 'orders#index'
  get 'my_orders' => 'orders#user_orders'
  
  post 'subcategories/create' => 'subcategories_create_path'
  
  post 'cart/add' => 'cart#add'
  post 'cart/add/:id' => 'cart#add'
  post 'cart/remove/:id' => 'cart#remove'
  post 'cart' => 'cart#index'
  post 'cart/add_amount' => 'cart#add_amount'
  resources :subcategories
  resources :products
  
  post '/update_order/:id' => "orders#update_order", as: :update_order
  
  

end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  before_action :find_cart
  
  def index
    filter_by_category
      
    @search_term = params[:q]  
    if @search_term
      @products = @products.search(@search_term)
      @category_title = 'Svi proizvodi'
    end
      
    if params[:sort] && params[:sort] == 'desc'
      @products = @products.order('price DESC')
    else
      @products = @products.order('price ASC')
    end
    @products = @products.paginate(page: params[:page], per_page: 12)
  end 

  def show
    @product = Product.find(params[:id])
  end
  
  def filter_by_category
    if params[:sub]
      @products = Product.filter(false, params[:sub])
      @category_title = Subcategory.find_name(params[:sub])
    elsif params[:cat]
      @products = Product.filter(true, params[:cat])
      @category_title = Category.find_name(params[:cat])
    else
      @products = Product.get_all
      @category_title = 'Svi proizvodi'
    end
  end
  
  def from_category
    filter_by_category
    if params[:sort] && params[:sort] == 'desc'
      @products = @products.order( 'price DESC' )
    else
      @products = @products.order( 'price ASC' )
    end
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/catalog_helper.rb
module CatalogHelper
  def sort(value)
    fetch_products_path(params.merge(sort: value).except(:controller, :action))
  end
  
  def no_products
    if @products.count() == 0
      return true
    end
    return false
  end
  
end

app/views/catalog/_products.html.erb
<% @products.each do |product| %>
    <div class="col-md-4 mt18"><!--ITEM-->
        <div class="col-md-12 item-card">
            <% if product.attachments %>
                <div class="col-md-12 no-padding">
                    <ul class="lightSlider">
                        <% product.attachments.each do |item| %>
                            <li data-thumb="<%= item.image.url(:thumb) %>" 
                                class="relative">
                                <%= image_tag item.image.url(:large), 
                                              class: "image" %>
                                <% unless item.available%>
                                    <div class="out-of-stock_img-label">
                                        Trenutno nema na lageru
                                    </div>
                                <% end %>
                            </li>
                        <%end%>
                    </ul>
                </div>
            <% end %>
            <%= link_to catalog_show_path(:id => product), 
                        class: "pointer" do %>
                <div class="col-md-12 cat-card-details">
                    <div class="va-child">
                        <span class="fs20 d-block">
                            <%= product.name %>
                        </span>
                        <span class="fs14 d-block">
                            <%= render partial: 'shared/price_format', 
                                       locals: { price: product.price} %> 
                            <span class="lw fs14">
                                <%= product.get_measure_type %>
                            </span>
                        </span>
                    </div>
                    <div class="va-helper"></div>
                </div>
            <% end %>
        </div>
    </div><!--ITEM END-->
<% end %>
   

app/views/catalog/from_category.js.erb
$("#products").html("<%= j render('products') %>");
$('.item-card').hover(function(){
        $(this).find('.cat-card-details').toggleClass('card-details-btn');
    });
// SLIDER STUFF
     $('#lightSlider').lightSlider({
        gallery: true,
        item: 1,
        loop: false,
        slideMove: 1,
        slideMargin: 0,
        enableDrag: true,
        easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
        speed: 800,
        thumbItem: 8,
        responsive: [{
            breakpoint: 800,
            settings: {
                item: 1,
                slideMove: 1,
                slideMargin: 6,
            }
        }, {
            breakpoint: 480,
            settings: {
                item: 1,
                slideMove: 1
            }
        }]
    });
    
    $('.lightSlider').each(function() {
        $(this).lightSlider({
            gallery: true,
            item: 1,
            loop: false,
            slideMove: 1,
            slideMargin: 0,
            enableDrag: true,
            easing: 'cubic-bezier(0.25, 0, 0.25, 1)',
            speed: 800,
            thumbItem: 8,
            responsive: [{
                breakpoint: 800,
                settings: {
                    item: 1,
                    slideMove: 1,
                    slideMargin: 6,
                }
            }, {
                breakpoint: 480,
                settings: {
                    item: 1,
                    slideMove: 1
                }
            }]
        });
    });

app/views/catalog/index.html.erb
<div class="col-md-12 page-head-sm">
    <h3><%= @category_title %></h3> 
</div>
<% if !no_products %>
    <div class="col-md-12">
        <div class="col-md-3 dropdown">
            <span class="dropdown-toggle" type="button" data-toggle="dropdown">
                <span id="filter">Sortiraj</span>
                <span class="caret"></span>
            </span>
            <ul id="menu" class="dropdown-menu scrollbar">
                <li class="divider"></li>     
                <li>
                    <%= link_to 'Po ceni (najniža)', 
                                sort('asc'), 
                                class:"ellipsis dropdown-menu-a", 
                                remote: true %>
                </li>
                <li>
                   <%= link_to 'Po ceni (najviša)', 
                               sort('desc'), 
                               class:"ellipsis dropdown-menu-a", 
                               remote: true %> 
                </li>
            </ul>
        </div>
    </div>
<% end %>
<div id = "products" class="col-md-12 no-padding mt18"> <!--ITEM LIST-->
    <%= render "products" %>
    <% if no_products %>
        <div class="product-null-state">
            <span class="glyphicon glyphicon-book d-block mb22"></span>
            Trenutno nema proizvoda pod ovom kategorijom
        </div>
    <% end %>
</div>
<div class="col-md-12 col-sm-12 col-xs-12 ct">
    <%= will_paginate @products, 
                      previous_label:'<span class="glyphicon glyphicon-arrow-left"></span>', 
                      next_label: '<span class="glyphicon glyphicon-arrow-right"></span>' %>
</div>

app/views/catalog/show.html.erb
<%= form_tag url_for(:controller => 'cart', :action => 'add'), 
             id: "add_to_cart_form" do %>
    <%= hidden_field :product, :id, value: @product.id  %>
    <%= hidden_field_tag :color %>
    <div class="col-md-6 mt45 ">
        <ul class="lightSlider">
            <% @product.attachments.each do |item| %>
                <li data-thumb="<%= item.image.url(:large) %>" class="relative">
                    <%= image_tag item.image.url(:large), 
                                  class: "image", 
                                  alt: item.get_file_name() %>
                    <% unless item.available %>
                        <div class="out-of-stock_img-label" 
                             id="<%= item.get_file_name_underscore() %>">
                            Trenutno nema na lageru
                        </div>
                    <% end %>
                </li>
            <%end%>
        </ul>
    </div>
    <div class="col-md-6 mt45">
        <div class="col-md-12 ct mb22">
            <h3 class="item-title">
                <%= @product.name %>
            </h3>
            <h4>
                <div class="fs20 lw">
                    <span id="price">
                        <%= render partial: 'shared/price_format', 
                                   locals: { price: @product.price} %>
                    </span>
                    <span class="light-text fs18 "> 
                        <%= @product.get_measure_type %>
                    </span>
                </div>
            </h4>
        </div>
        <div class="col-md-12">
            <div class="col-md-6 choose-box">
                Izabrana nijansa:
                </br>
                <div id="chosen" class="link-c b mt18 ellipsis"></div>
            </div>
            <div class="col-md-6 choose-box">
                Unesite količinu:
                </br>
                <% if @product.piece %>
                    <%= text_field_tag :amount, 
                                       '1', 
                                       class:"form-control ct atc-input link-c b mt18 fs18", 
                                       id: 'amount', placeholder: "komada",
                                       min: '0', 
                                       type: 'number', 
                                       step: '1'%>
                <% else %>
                <%= text_field_tag :amount, 
                                   '1', 
                                   class:"form-control ct atc-input link-c b mt18 fs18", 
                                   id: 'amount', 
                                   placeholder: "metara",
                                   min: '0', 
                                   type: 'number', 
                                   step: '0.5'%>
                <% end %>
            </div>
            <div class="col-md-12 item-total">
                Total
                <br>
                <span id="total" class="fs24" >
                    <%= render partial: 'shared/price_format', 
                               locals: { price: @product.price} %>
                </span>
            </div>
            <div class="col-md-12 no-padding mt45">
                <%= button_tag type: "button", 
                               class: "button button-submit", 
                               id:"add_to_cart_submit" do %>
                    <span class='glyphicon glyphicon-repeat spin hide-at-first'>
                    </span> 
                    Dodaj u korpu 
                    <span class="glyphicon glyphicon-shopping-cart fs14"></span>
                <% end %>
            </div>
            <div class="col-md-12 item-description">
                <%= @product.description %>
            </div>
        </div>
    </div>
<%end%>